// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsIoanxvaqoP8WDyjfnJ0ygANmjsPzKeg',
    appId: '1:139599331276:web:62b86e8f22a8a96751a769',
    messagingSenderId: '139599331276',
    projectId: 'my-quick-quiz-app',
    authDomain: 'my-quick-quiz-app.firebaseapp.com',
    storageBucket: 'my-quick-quiz-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0hR5KVPELNmPNmrBSwZ4ACIUcXFxluw',
    appId: '1:139599331276:android:51fefde5b7076de651a769',
    messagingSenderId: '139599331276',
    projectId: 'my-quick-quiz-app',
    storageBucket: 'my-quick-quiz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAht7KY4d2J1RO8z0jUgVTh_b6JQivdeyU',
    appId: '1:139599331276:ios:cbe99cb2e75e995751a769',
    messagingSenderId: '139599331276',
    projectId: 'my-quick-quiz-app',
    storageBucket: 'my-quick-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.shortquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAht7KY4d2J1RO8z0jUgVTh_b6JQivdeyU',
    appId: '1:139599331276:ios:cbe99cb2e75e995751a769',
    messagingSenderId: '139599331276',
    projectId: 'my-quick-quiz-app',
    storageBucket: 'my-quick-quiz-app.firebasestorage.app',
    iosBundleId: 'com.example.shortquiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsIoanxvaqoP8WDyjfnJ0ygANmjsPzKeg',
    appId: '1:139599331276:web:f2733736645888dd51a769',
    messagingSenderId: '139599331276',
    projectId: 'my-quick-quiz-app',
    authDomain: 'my-quick-quiz-app.firebaseapp.com',
    storageBucket: 'my-quick-quiz-app.firebasestorage.app',
  );
}
